inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'db/schema.rb'

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false
  
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'feature']
